version: '3.9'

services:
  db:
    container_name: '${APP_NAME}-db'
    image: postgres
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  storage_db:
