name: Faça uma requisição no Render a cada 15 minutos

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  render-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Paginate Posts
        run: curl https://jedais-tec-api.onrender.com/v1/post/paginate
